# The configuration file for Log Begone

[logbegone]
# If a log message has one of these phrases, it will be filtered out from logging
phrases = ["Disconnecting VANILLA connection attempt", "Channels ", "Parsing error loading recipe", "has a broken icon, loading default icon", "Invalid mod icon for icon source", "Mod icon must be a square", "The Recipe View has more input slots", "Hanging entity at invalid position:"]

# If a log message matches one of these regex patterns, it will be filtered out from logging. EX: 
regex = ["Disconnecting VANILLA connection attempt", "Channels ", "Parsing error loading recipe"]